apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: globex-mobile-gateway
  namespace: globex-apim-user1
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: globex-mobile-gateway
  rules:
    authentication:
      "keycloak-users":
        jwt:
          issuerUrl: <KEYCLOAK_URL>
    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  selector: auth.identity.sub
