apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: globex-mobile-gateway
  namespace: globex-apim-user1
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: globex-mobile-gateway
  limits:
    "per-user":
      rates:
        - limit: 50
          window: 10s
      counters:
        - expression: auth.identity.userid
