apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: echo-api-rlp
  namespace: echo-api
spec:
  limits:
    echoa-api:
      rates:
        - limit: 10
          window: 10s
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: echo-api
